### ISSUE TITLE
Améliorer la précision de temps de réponse

### ISSUE THREAD

**Issue by octo-topi** [1024pix/pix-db-stats#8]
Suite à https://github.com/1024pix/pix-db-stats/pull/7#pullrequestreview-737207013
Ex: Utiliser l'API de performance
https://blog.logrocket.com/experimental-node-js-testing-the-new-performance-hooks-31fcdd2a747e/

**Comment by francois2metz** [comment]
Il ne semble pas que nous ayons besoin de cette précision. A rouvrir si une implémentation est prévue ou en cours.
